var price = 300;
var name = "saifur Rahman";
var friendsName = ["siam","rakib"];
var isSingle= false;
var fruits =['apple','banana','orange'];
var bananaIndex = fruits.indexOf('banana');
console.log(bananaIndex);
fruits[bananaIndex]='mango';
console.log(fruits[bananaIndex]);
console.log(fruits);
fruits.pop();
fruits.push('watermelon');
console.log(fruits);
